version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    depends_on:
      - redis

  fetcher:
    build:
      context: ./fetcher
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - kryplproject_default

  redis:
    image: redis:latest
    hostname: redis
    
networks:
  kryplproject_default:
    external: true