//========== USER ACTION ==========
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_API_KEYS = 'GET_API_KEYS';
export const EDIT_API_KEY = 'EDIT_API_KEY';
export const DELETE_API_KEY = 'DELETE_API_KEY';


//========== ASSET ACTION ==========
export const GET_ASSETS = 'GET_ASSETS';
export const UPDATE_PAPER_ASSETS = 'UPDATE_PAPER_ASSETS';
export const UPDATE_REAL_ASSETS = 'UPDATE_REAL_ASSETS';


//========== MARKET DATA ACTION ==========
export const GET_MARKET_DATA = 'GET_MARKET_DATA';
export const GET_CURRENCY_VALUES = 'GET_CURRENCY_VALUES';


//========== OVERVIEW ACTION ==========
export const GET_PAPER_OVERVIEW = 'GET_PAPER_OVERVIEW';
export const GET_PAPER_STRATEGIES = 'GET_PAPER_STRATEGIES';
export const REGISTER_PAPER_STRATEGY = 'REGISTER_PAPER_STRATEGY';

export const GET_REAL_OVERVIEW = 'GET_REAL_OVERVIEW';
export const GET_REAL_STRATEGIES = 'GET_REAL_STRATEGIES';
export const REGISTER_REAL_STRATEGY = 'REGISTER_REAL_STRATEGY';

export const GET_PAPER_VALUE_HISTORY = 'GET_PAPER_VALUE_HISTORY';
export const GET_REAL_VALUE_HISTORY = 'GET_REAL_VALUE_HISTORY';

//========== STRATEGY ACTION ==========
export const GET_PAPER_STRATEGY = 'GET_PAPER_STRATEGY';
export const GET_REAL_STRATEGY = 'GET_REAL_STRATEGY';
export const GET_STRATEGY_TRADES = 'GET_STRATEGY_TRADES';
export const GET_STRATEGY_VALUE_HISTORY = 'GET_STRATEGY_VALUE_HISTORY';
export const STOP_STRATEGY = 'STOP_STRATEGY';